### ISSUE TITLE
help with lanugage servers....

### ISSUE THREAD

**Issue by Vaisakhkm2625** [LamprosPitsillos/nixos-config#1]
Hi Lampros,

i have been checking your config and found you have language servers in your configuration.nix... 
but 'typstfmt' and 'typst-live' wheren't there in search.nix.org... can you please tell how did you added it there??

**Comment by LamprosPitsillos** [comment]
Hi,
They are , just not on the normal channel, only in unstable for now.
[Typst](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=Typst)

**Comment by Vaisakhkm2625** [comment]
> Hi, They are , just not on the normal channel, only in unstable for now. [Typst](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=Typst)

sorry for late replying.. thanks...
